# Generated by Django 6.0.3 on 2026-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
