# Generated by Django 6.0.3 on 2026-04-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_destination_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='is_popular',
        ),
    ]
