# Generated by Django 6.0.3 on 2026-04-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_destination_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='location',
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
