# Generated by Django 6.0.3 on 2026-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_destination_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
