# Generated by Django 6.0.3 on 2026-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_destination_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
